### ISSUE TITLE
Rotate Image

### ISSUE THREAD

**Issue by pranavbharadwaj007** [Hacktoberfest-SCE/Lets-contribute#45]
# **You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).**

## You have to rotate the image in-place, which means you have to modify the input 2D matrix directly. DO NOT allocate another   2D matrix and do the rotation.

![Capture](https://user-images.githubusercontent.com/55646472/94895483-2617a500-04a9-11eb-8f59-5e85e2234203.PNG)

**Comment by Pacifier25** [comment]
can i work in this issue?

**Comment by Pacifier25** [comment]
i have writen this code already in c++

**Comment by babitha667** [comment]
I would like to contribute please assign me

**Comment by Pacifier25** [comment]
i have another soln plz check #54

**Comment by pranavbharadwaj007** [comment]
@Pacifier25 great I will look into that as well
